// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "H-ours24",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "H-ours24",
            targets: ["AppModule"],
            bundleIdentifier: "dayjack.H-ours24",
            teamIdentifier: "UG6UT639QH",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .photoLibraryAdd(purposeString: "Unknown Usage Description")
            ],
            appCategory: .education
        )
    ],
    dependencies: [
        .package(url: "https://github.com/airbnb/lottie-ios.git", "4.0.0"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Lottie", package: "lottie-ios")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
